extends SceneTree
func _initialize() -> void:
	call_deferred("run")
func frames(count: int) -> void:
	for i in range(count):
		await physics_frame
func run() -> void:
	var game = load("res://scripts/game.gd").new()
	root.add_child(game)
	game.sound.volume = 0
	var location := "user://qa-training-%d" % Time.get_ticks_usec()
	DirAccess.make_dir_recursive_absolute(location)
	game.local_profile = load("res://scripts/local_profile.gd").new(location + "/results")
	game.checkpoint.path = location + "/checkpoint.dat"
	await process_frame
	game.start_solo()
	assert(game.suspend_solo())
	var saved := FileAccess.get_file_as_bytes(game.checkpoint.path)
	game.start_training()
	var actor = game.actors[1]
	assert(game.training.step == 0 and game.actors.size() == 1)
	assert(not game.suspend_solo())
	game.ui.set_pause(true)
	assert(not game.ui.checkpoint_save_button.visible)
	game.ui.set_pause(false)
	Input.action_press("forward")
	await frames(90)
	Input.action_release("forward")
	assert(game.training.step == 1)
	Input.action_press("crouch")
	await frames(3)
	Input.action_release("crouch")
	assert(game.training.step == 2 and game.actors.size() == 4)
	game.damage(game.actors[-1], 1000, 1, true, false, "FRAG")
	assert(game.actors[-1].alive and game.training.kills == 0)
	actor.switch_weapon(2)
	await frames(3)
	for id in [-1, -2, -3]:
		var target = game.actors[id]
		var direction: Vector3 = (target.aim_position() - actor.aim_position()).normalized()
		actor.yaw = atan2(-direction.x, -direction.z)
		actor.pitch = asin(direction.y)
		actor.fire_left = 0
		actor.recoil = 0
		game.shoot(actor)
		await frames(3)
		assert(not target.alive)
	assert(game.training.step == 3)
	actor.position = Vector3(0, 0.02, 14)
	await frames(2)
	assert(game.pickup(actor))
	await frames(2)
	assert(game.training.step == 4)
	actor.reload_weapon()
	await frames(190)
	assert(game.training.step == 5 and actor.health == 40)
	game.damage(actor, 1000, 0, true)
	assert(actor.health == 40)
	actor.heal()
	await frames(220)
	assert(game.training.step == 6)
	assert(game.throw_grenade(actor))
	await frames(180)
	assert(game.training.step == 7)
	assert(game.throw_grenade(actor, 1))
	await frames(270)
	assert(game.training.step == 8)
	game.ui.set_map(true)
	await frames(2)
	game.ui.tactical_map.waypoint = Vector2(10, 10)
	await frames(2)
	game.ui.set_map(false)
	await frames(2)
	assert(game.training.step == 9 and game.phase == "training_complete")
	game.save_local_operation()
	assert(game.local_outbox.is_empty())
	assert(not DirAccess.dir_exists_absolute(location + "/results/records/" + game.match_id))
	game.leave()
	assert(game.training == null and saved == FileAccess.get_file_as_bytes(game.checkpoint.path))
	assert(game.resume_solo())
	game.ui.set_pause(false)
	assert(game.actors.size() == 16 and game.training == null)
	game.local_profile = null
	game.start_training()
	game.start_solo()
	assert(game.training == null and game.actors.size() == 16)
	print("TRAINING_RULES_PASS")
	game.request_quit()
